runtime: custom
env: flex
service: app

resources:
  cpu: 4
  memory_gb: 7.5
  disk_size_gb: 10
  volumes:
  - name: ramdisk1
    volume_type: tmpfs
    size_gb: 0.5

automatic_scaling:
  min_num_instances: 0
  max_num_instances: 5
  cool_down_period_sec: 120
  cpu_utilization:
    target_utilization: 0.6

includes:
- secrets.yaml