server:
  port: 8080

spring:
  profiles:
    active: "dev"

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

amazon:
  aws:
    accesskey:
    secretkey:
    bucketName: mediafilescad

---

spring:
  profiles: dev

---

spring:
  profiles: prod
