server:
  port: 8080

spring:
  profiles:
    active: "dev"
  session:
    store-type: redis
  redis:
    host: redis-19050.c17.us-east-1-4.ec2.cloud.redislabs.com
    port: 19050
    password:

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

amazon:
  aws:
    accesskey:
    secretkey:
    bucketName: mediafilescad

---

spring:
  profiles: dev

---

spring:
  profiles: prod
