package de.htwg.klaut.backend.model.db;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;

@DynamoDBTable(tableName = "user")
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class CloudUser {

    @Id
    private CompositeId compositeId;

    @DynamoDBAttribute
    private String email;

    @DynamoDBAttribute
    private String firstName;

    @DynamoDBAttribute
    private String lastName;

    @DynamoDBAttribute
    private String passwordHash;

    @DynamoDBHashKey(attributeName = "organization")
    public String getOrganization() {
        return compositeId.getOrganization();
    }

    public void setOrganization(String organization) {
        if (compositeId == null) {
            compositeId = new CompositeId();
        }
        this.compositeId.setOrganization(organization);
    }

    @DynamoDBRangeKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return compositeId.getId();
    }

    public void setId(String sortKey) {
        if (compositeId == null) {
            compositeId = new CompositeId();
        }
        this.compositeId.setId(sortKey);
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getPasswordHash() {
        return passwordHash;
    }

    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
    }
}
