package de.htwg.klaut.backend.model.db;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import de.htwg.klaut.backend.model.ModelParamConverter;
import de.htwg.klaut.backend.model.ModelParams;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;

import java.io.Serializable;
import java.util.Set;

@DynamoDBTable(tableName = "model")
@AllArgsConstructor
@NoArgsConstructor
/* IMPORTANT: Do not generate setter and getter here or composite key for DynamoDBs will not work */
public class Model implements Serializable {

    @Id
    private ModelCompositeId compositeId;

    @DynamoDBAttribute
    private String name;

    @DynamoDBAttribute
    private String algorithm;

    @DynamoDBAttribute
    private String description;

    @DynamoDBTypeConverted(converter = ModelParamConverter.class)
    private ModelParams params;

    @DynamoDBAttribute
    private String modelUrl;

    @DynamoDBAttribute
    private Set<String> sourceUrls;

    @DynamoDBHashKey(attributeName = "organization")
    public String getOrganization() {
        return compositeId.getOrganization();
    }

    public void setOrganization(String organization) {
        if(compositeId == null){
            compositeId = new ModelCompositeId();
        }
        this.compositeId.setOrganization(organization);
    }

    @DynamoDBRangeKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return compositeId.getId();
    }

    public void setId(String sortKey) {
        if(compositeId == null){
            compositeId = new ModelCompositeId();
        }
        this.compositeId.setId(sortKey);
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAlgorithm() {
        return algorithm;
    }

    public void setAlgorithm(String algorithm) {
        this.algorithm = algorithm;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public ModelParams getParams() {
        return params;
    }

    public void setParams(ModelParams params) {
        this.params = params;
    }

    public String getModelUrl() {
        return modelUrl;
    }

    public void setModelUrl(String modelUrl) {
        this.modelUrl = modelUrl;
    }

    public Set<String> getSourceUrls() {
        return sourceUrls;
    }

    public void setSourceUrls(Set<String> sourceUrls) {
        this.sourceUrls = sourceUrls;
    }
}
