package de.htwg.klaut.backend.model.db;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;
import lombok.NonNull;
import lombok.RequiredArgsConstructor;

@DynamoDBTable(tableName = "organization")
@Data
@RequiredArgsConstructor
public class Organization {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String key;

    @NonNull
    @DynamoDBAttribute
    private String name;

    @NonNull
    @DynamoDBAttribute
    private String iconUrl;
}
