package de.htwg.klaut.backend.model.db;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;

@DynamoDBTable(tableName = "organization")
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class Organization {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String key;

    @NonNull
    @DynamoDBAttribute
    private String name;

    @NonNull
    @DynamoDBAttribute
    private String iconUrl;

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = SubscriptionConverter.class)
    private SubscriptionInformation subscriptionInformation;
}
